services:
  sql-injection:
    build: ./sql-injection
    ports:
      - "5000:5000"
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    networks:
      - sql_net

  broken-auth:
    build: ./broken-auth
    ports:
      - "5001:5000"
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    networks:
      - auth_net

  privilege-escalation:
    build: ./privilege-escalation
    ports:
      - "5002:5000"
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    networks:
      - priv_net

  misconfiguration:
    build: ./misconfiguration
    ports:
      - "5003:5000"
    environment:
      - DEBUG_MODE=false
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    networks:
      - misconf_net

networks:
  sql_net:
  auth_net:
  priv_net:
  misconf_net:

